README.md

The link to preview the book is available on the same page

Add link for Stephen Fleming's book

---

README.md

👋 Hey there @visenger, I hope you don't mind me opening a PR? I've done two small things to this (awesome!) collection you've put together.
1. I fixed a broken link to the talks section
2. I've added an article that I wrote to the `Product Management for ML/AI` section.
Hope that's cool 🙏

Add ML for Product Managers article (& fix link)

---

README.md

Useful resource that summarizes research and articles in the field of AI ethics from Q2 2020

Added State of AI Ethics June 2020 report from MAIEI

---

README.md

Hello @visenger we will be moving our blog to trainindatablog.com, so the current link in your readme will no longer be available. Please accept my PR with the new link :)

Update README.md with new link

---

README.md

Hey @visenger ,
thanks for the nice collection of resources!
Since it is getting quite a bit of attention lately, I added some links related to the role of Feature Stores in the MLOps process.
Hope the links fit the goals of your repo :)

Add feature store for ML content

---

README.md

- update paper numbering
- add links to paper pdf file

Updated MLOps Papers section

---

README.md

Hey @visenger ,
Thanks for the amazing resource list!
I'd like to add some blog posts from Medium, a Robust and Responsible AI community and a new ML system to your repo.
Cheers!

Add links about RqsrdAI, data logging blogs and WhyLabs

---

README.md

Hey @visenger 
just adding a missing link of a book.
Cheers!

Add missing link to book

---

README.md

Hey @visenger 
just removing a dead link.
Cheers!

Removing dead link from ML list

---

README.md

- add 2nd part of the **ML Infrastructure Tools for Production**

Update MLOps: Infrastructure section

---

README.md

https://github.com/ibm-cloud-architecture/refarch-ml-ops

IBM ML Operationalization Starter Kit

---

README.md

While it's not focused solely on MLOps, there are a lot of people interested in this topic

DataTalks.Club

---

README.md

As suggested on Twitter, I'm adding my "Deploying Machine Learning Models: A Checklist" to the list of the resources. I've put it under the "MLOps Articles", since I saw similar things in this section.

Adding "Deploying Machine Learning Models: A Checklist"

---

README.md

As per Tweet: https://twitter.com/visenger/status/1354113077285941248

PR-ing in Data Science Bootstrap KB and Data Science Programming Newsletter

---

README.md

Added the following papers:
- Challenges in deploying machine learning: a survey of case studies. (https://arxiv.org/abs/2011.09926)
- Challenges in the deployment and operation of machine learning in practice. (https://aisel.aisnet.org/ecis2019_rp/163/)
- On Challenges in Machine Learning Model Management. (https://web.kaust.edu.sa/Faculty/MarcoCanini/classes/CS290E/F19/papers/challenges.pdf)

Added three papers to the "MLOps papers" section

---

README.md

Started to reformat the MLOps Papers section as described in issue [#42](https://github.com/visenger/awesome-mlops/issues/42)

Reformat MLOps Papers section

---

README.md

added Synthetic Data Community

Added MLOps community

---

README.md

Added Engineering MLOps book and MLOps: Automated Machine Learning talk.
Please add them.

added Engineering MLOps book and talk

---

README.md

Hey! Please consider adding my book, "Effective Data Science Infrastructure" to the MLOps Books list. Thanks!

Add Effective Data Science Infrastructure to Books

---

README.md

Hey there! Please consider adding [MLOps Guide](https://mlops-guide.github.io/) to your MLOps list! 
MLOps Guide has two objectives:
* Introducing MLOPs Theory
* Implementation Tutorial using DVC, CML, IBM Watson and Github Actions
The Project Architecture
Thanks for your attention 😁

Added mlops guide

---

README.md

Capitalize Aporia

---

README.md

I found this blog post to be very detailed and useful, and think that others would benefit from it, too.

Add blog post about unit testing DL code

---

README.md

added nimblebox blog about MLOps tools

added nimblebox blog

---

README.md

adding computer vision newsletter

---

README.md

added to Machine Learning,MLOps Articles,MLOps: Data Engineering (DataOps),MLOps: Testing, Monitoring and Maintenance.

added a few articles

---

papers.md

Adds "Socio-Technical Anti-Patterns in Building ML-Enabled Software: Insights from Leaders on the Forefront" to papers.md
Thank you for maintaining this amazing resource!

Add paper on socio-technical anti-patterns

---

README.md

before:
```
[Meet Michelangelo: Uber’s Machine Learning Platform](https://eng.uber.com/michelangelo/)
```
after:
```
[Meet Michelangelo: Uber’s Machine Learning Platform](https://www.uber.com/blog/michelangelo-machine-learning-platform/)
```

refactor(README.md): Uber's Michelangelo article link change

---

README.md

Updated a broken link and adding an article on cloud deployment using IaC for better automation and scale.

Adding an article

---

README.md

Hello,
Ive updated the list of books to include the previous year (2023), if there's any more editions please add. 
Thanks for the awesome list.

Added MLOps books published for 2023.

---

README.md

Hey there,
I've added my Newsletter to the list of MLOps resources. Hope that's okay! It's free and only there to provide value.
Thanks for considering and great collection!
Best,
Sebastian

Added MLOps Insights Newsletter

---

README.md

Added free Udacity LLMOps course 
Signed-off-by: Abby Morgan abigailm@comet.com

Add Udacity LLMOps course
